/**
 * RFC 7807 Problem Details for HTTP APIs
 * @see https://tools.ietf.org/html/rfc7807
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type.
   * Should resolve to human-readable documentation.
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server.
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance: string;

  /**
   * ISO 8601 timestamp when the error occurred.
   */
  timestamp: string;

  /**
   * UUID of the request that generated the error (for correlation).
   */
  requestId: string;

  /**
   * Additional problem-specific extension members
   */
  [key: string]: unknown;
}
